apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ebbuulqei-python 
  janus-idp.io/tekton: ebbuulqei-python
  backstage.io/kubernetes-id: ebbuulqei-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ebbuulqei-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml